### ISSUE TITLE
no issue just great work

### ISSUE THREAD

**Issue by BlackStump** [Stephan3/dwc2-for-klipper#1]
I have installed on a Replicape/BeagleBone Black with Debian.
The install instruction are great, the installation of gunzip is not needed with Debian well at least for the version I was using BBB-9.2

I have been using for a couple of hours doing small prints with no issues DWC2 is quite nice actually like it better then DWC1

I have no issues to report it is fast to load and operate compared to Octoprint

awesome work 
thank you

**Comment by Stephan3** [comment]
good to hear.
