### ISSUE TITLE
What IS DWC2?

### ISSUE THREAD

**Issue by sixtyfive** [Stephan3/dwc2-for-klipper#102]
Seems to be ungooglable. The only thing I can find is https://github.com/Duet3D/DuetWebControl, which I'm not sure is the DWC1 the README is referring to. As this repository on its own cannot possibly contain a complete web-app as is shown in the screenshots, I'm wondering what the unmentioned prerequisite might be? (If it's not already obvious, I'm not a Duet printer owner, otherwise I might well know all these?)

**Comment by Stephan3** [comment]
Its duet Webcontrol. google for it, its on github
