### ISSUE TITLE
G10 firmware retraction

### ISSUE THREAD

**Issue by BlackStump** [Stephan3/dwc2-for-klipper#16]
The duet firmware allows G10 without any parameters to be parsed as a firmware retraction and with parameter as you have implement temperature control.
I have a klipper macro using G10/11 for retract, unretract, G11 works if command is issued in DWC 
G10 doesn't work, is it possible to allow G10 without parameters to be parsed?

**Comment by Stephan3** [comment]
This should work as is in a gcodefile as its processed by Klipper itself. Just FYI this is better than using your macro.

https://github.com/KevinOConnor/klipper/pull/1617

**Comment by BlackStump** [comment]
thanks I will have a look
