### ISSUE TITLE
3 extruders, one hotend

### ISSUE THREAD

**Issue by dystechnic** [Stephan3/dwc2-for-klipper#17]
Hi,

First of all, Thanks for the work! I love this, this is so much more informational and faster than Octoprint.

I have a printer with 3 extruders and a 3-in 1-out switching hotend. So I only use one heater shared over the 3 extruders. So I don't need 3 hotends showing up in the web-interface. 
Is it possible not only to check in printer.cfg if there are multiple extruder definitions but also check if they share the same heater? In printer.cfg this is configured as `shared_heater: extruder0` in the [extruder1] and [extruder2] section.
I that is the case you could only show extruder0 and omit the other extruders.

Thanx.

**Comment by Stephan3** [comment]
Hi.

Basicaly everything is possible. I thing the 2 extruders are listed with invalid temperatures or do they all have the same temperature?

- Stephan

**Comment by dystechnic** [comment]
Hi,

All extruders show the same temperature.

Ed.

**Comment by Stephan3** [comment]
as i am not going to work on this, this will close.
