### ISSUE TITLE
linux host shutdown command

### ISSUE THREAD

**Issue by BlackStump** [Stephan3/dwc2-for-klipper#19]
Is it possible add a shutdown and reboot command so as to shutdown the host from within DWC
ie sudo shutdown -h now
ie sudo shutdown -r now

also babysteps is not working  MOVE=1 needs to be added as per change log 20190520
https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Changes.md

Thank you

**Comment by dystechnic** [comment]
I second that request. That would be a nice enhancement.

**Comment by zmrde** [comment]
I also would like to see run native linux commands.

**Comment by Stephan3** [comment]
I Agree with the MOVE=1 thing you mentioned. But why do we need native Linux commands? Next thing i am affraid of is, the day we merge, this might become a problem.

**Comment by BlackStump** [comment]
If it is any concern with a merge then I agree leave it out for now!
The reason I asked is at the moment I use DWC then when I want to shutdown the printer I get out of DWC and open up Putty to log in to the Orangepi enter username and password issue the "sudo shutdown -h" enter password again and wait for the shutdown and power off. 
I have been doing this for sometime so I can continue but it would be nice to be able to shut it down from DWC .
I would say that is the only thing I miss from Octoprint.

Thanks again for your work
Cheers

**Comment by manu7irl** [comment]
maybe parsing the command from a macro could be possible

**Comment by Stephan3** [comment]
I dont think that i will make that happen. You should ask Kevin if klipper should support hostcommands by gcode.
