### ISSUE TITLE
Height Map co-ordinates do not match bed width

### ISSUE THREAD

**Issue by Oddy9923857** [Stephan3/dwc2-for-klipper#20]
I have a 310x310 print bed and when I probe the bed for a mesh it is displayed in the height map page; however if I click on a point it is not the correct X & Y co-ordinate. Otherwise the height map is correct, just it seems to get the X & Y co-ordinates off (like it is scaling to a smaller bed size (100x100).

**Comment by Stephan3** [comment]
Tested today on a 300x300 Voron 2 and a 350x350 voron 2 and works for me. So not sure what it is.
Once you load your map, klipper dwc2 creates a heightmap.csv If you can grab that file, we can take a look at it.

**Comment by lenne0815** [comment]
having the same problem, in the csv there are 10 x 10 points, i only set up 4 x 4
[heightmap.zip](https://github.com/Stephan3/dwc2-for-klipper/files/3964869/heightmap.zip)
Max z Probed point is 74.5 in the gui, even though the csv says 224.98

Ah, i think the spacing is calculated wrongly, the points are much further apart then 21.498 it displays 10 points but i only set up 4, thats probably why.
