### ISSUE TITLE
Revert to DWC1

### ISSUE THREAD

**Issue by Scottbg1** [Stephan3/dwc2-for-klipper#24]
In the 'Machine Specific Settings' there is an option to Divert to DWC1.

Is there a way to set it for it to default to DWC1 when connecting?

**Comment by Stephan3** [comment]
Yes directly navigation to the link that button points. I think it’s reprap.html

**Comment by Scottbg1** [comment]
Of course. I didn't think about that.
Works  as described.

Thank you!
