### ISSUE TITLE
Failed to maintain connection

### ISSUE THREAD

**Issue by supernielsen** [Stephan3/dwc2-for-klipper#25]
Hello..
First of all thank you for dwc2 i am pretty happy about it and have been using it for some time..

However i get the fault failed to maintain connection oretty much constantly.. I get on the web interface after 40 seconds i get this error and i cant input any data..
If i reopen the window in the browser it works again for 30 seconds..

What can i do i never had this problem with octoprint and i can see on the pi that i have a very steady and stable internet connection.

**Comment by Stephan3** [comment]
Without a logfile i cant analyse what happend.
