### ISSUE TITLE
port to replicape

### ISSUE THREAD

**Issue by killisch** [Stephan3/dwc2-for-klipper#27]
Is anyone interested in working on porting DWC2 for Replicape to replace octoprint?

i don't have the skillset myself but would happily test or help out where possible.

**Comment by Stephan3** [comment]
Sorry but i dont have the knowledge of replicape to do so.

**Comment by BlackStump** [comment]
@killisch  Replicape is just hardware and is already supported by Klipper and works with @Stephan3 wonderful translator.
Your question would be better asking if porting to redeem which is the firmware created by the Replicape guys, and to be blunt poorly implemented and supported imho you would be better just going with klipper.
I suspect the answer will be no different in anycase.

**Comment by killisch** [comment]
Understood. Feel free to close this issue.
