### ISSUE TITLE
Could we use the last version of DWC ?

### ISSUE THREAD

**Issue by kakou-fr** [Stephan3/dwc2-for-klipper#28]
I just installed your fabulous port, and i fund that a version 2.0.2 is available.

Could I use it ?

https://github.com/chrishamm/DuetWebControl/releases/

**Comment by McZlik** [comment]
Yes this is possible, I'm running 2.0.2 without any problems!

**Comment by kakou-fr** [comment]
thks

**Comment by Stephan3** [comment]
i close this, updated to latest.
