### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc2' in file

### ISSUE THREAD

**Issue by gitxmax** [Stephan3/dwc2-for-klipper#32]
Hello,
Did a clean install of Ubuntu 18.04
Then followed the instructions posted here.
Klipper service is running, but /tmp/klippy.log is showing an error.
The web panel is down.

`pi@pi-pc:~$ cat /tmp/klippy.log
Starting Klippy...
Args: ['/home/pi/klipper/klippy/klippy.py', '/home/pi/printer.cfg', '-l', '/tmp/klippy.log']
Git version: 'v0.8.0-87-g0bfb655f-dirty'
CPU: 4 core Intel(R) Atom(TM) CPU  Z3735F @ 1.33GHz
Python: '2.7.15+ (default, Oct  7 2019, 17:39:04) \n[GCC 7.4.0]'
Start printer at Sat Nov  9 00:11:48 2019 (1573233109.0 8.4)
===== Config file =====
[virtual_sdcard]
path = /home/pi/sdcard

[web_dwc2]
printer_name = Reiner Calmund
listen_adress = 0.0.0.0
listen_port = 4750
web_path = dwc2/web
=======================
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 134, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 127, in _read_config
    self.try_load_module(config, section_config.get_name())
  File "/home/pi/klipper/klippy/klippy.py", line 110, in try_load_module
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 543
SyntaxError: Non-ASCII character '\xc2' in file /home/pi/klipper/klippy/extras/web_dwc2.py on line 543, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

**Comment by Stephan3** [comment]
Thanks for reporting.
please use latest git, its fixed
