### ISSUE TITLE
File list on LCD

### ISSUE THREAD

**Issue by rafaljot** [Stephan3/dwc2-for-klipper#38]
If you are using LCD there is a menu "SD Card". It lists files from folder /home/pi/sdcard
Unfortunately Klipper doesn't suport subfolders.

dwc2-for-klipper stores  all files in "gcodes" subfolder so I can't print uploaded files using LCD menu. 

I made little  workaround:
[virtual_sdcard]
path: /home/pi/sdcard/gcodes

`
#<-----><------>self.sdpath = self.configfile.getsection("virtual_sdcard").get("path", None)
<------><------>self.sdpath = config.get( 'sd_path', self.configfile.getsection("virtual_sdcard").get("path", None))
`

then:

[web_dwc2]
(...)
sd_path: /home/pi/sdcard

**Comment by Stephan3** [comment]
I am willing to add this. As you did this allready, does dwc realize that printing started when starting from lcd?

**Comment by Stephan3** [comment]
No answer since a month? you alive?

**Comment by rafaljot** [comment]
Sorry,
Unfortunately not. Over and over trying to reconnect
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/13086437/71529317-74799100-28e4-11ea-9861-56d298f56fbe.png">

**Comment by Stephan3** [comment]
Okay you are asking for "file list on LCD" and then you are talking about restarts.
What ever you did/doing it breaks thing. If i can help with code or take a look at logs, let me know.

**Comment by rafaljot** [comment]
Because this restart happens only during printing when I start it from file list on LCD. 
Yep, I'll try to manage this issue.

**Comment by Stephan3** [comment]
Then I need a loggile please

**Comment by trevjonez** [comment]
both sdcard lcd listing and the constant errors when a print is started via LCD are resolved by the combination of
https://github.com/KevinOConnor/klipper/pull/2767 and [Stephan3/dwc2-for-klipper#65](https://github.com/Stephan3/dwc2-for-klipper/pull/65)
