### ISSUE TITLE
Touch Screen GUI

### ISSUE THREAD

**Issue by ETE-Design** [Stephan3/dwc2-for-klipper#39]
Would like to connect a Touch Screen to my RPI, is there a GUI for your DWC2, or could you make one? Like TouchUI for OctoPi...

**Comment by Stephan3** [comment]
you can use a tablet

**Comment by ETE-Design** [comment]
So right now no Touch Screen Support for screens direct connected to RPI :-( Would like to use it with a "Small" screen...

**Comment by Stephan3** [comment]
Feel free to use any screen. You can launch an xserver and use the webif with touch interface. If you want a fullblown touchsupport feel free to code and release a solution.

-Stephan
