### ISSUE TITLE
'web_dwc2'  is not a valid configuration section

### ISSUE THREAD

**Issue by AbomShep** [Stephan3/dwc2-for-klipper#40]
I updated Klipper today (main branch) and DWC2 couldn't connect. "OK, I thought, it's been a long time and many changes, lets see if DWC2 has changed" It had, so I updated it as well. Now Klipper errors out with the infamous
>Config error
>Traceback (most recent call last):
>  File "/home/pi/klipper/klippy/klippy.py", line 134, in _connect
>    self._read_config()
>  File "/home/pi/klipper/klippy/klippy.py", line 131, in _read_config
>    pconfig.check_unused_options(config)
>  File "/home/pi/klipper/klippy/configfile.py", line 235, in check_unused_options
>    section,))
>Error: Section 'web_dwc2' is not a valid config section`

I made sure the link was still there, and did the sed commands to modify Klipper's file. The link and web_dwc2's permissions are good. Can't figure out what I'm doing wrong. I had this once before and it was an actual problem, so I'm logging this just in case.

chmod 777 for trouble-shooting purposes.
>pi@raspberrypi:~/klipper/klippy/extras $ ls -la web_dwc*
>lrwxrwxrwx 1 pi pi  37 Dec 29 18:57 web_dwc2.py -> /home/pi/dwc2-for-klipper/web_dwc2.py
>-rwxrwxrwx 1 pi pi 129 Dec 29 17:59 web_dwc2.pyc

>pi@raspberrypi:~/klipper/klippy/extras $ ls -la /home/pi/dwc2-for-klipper/web_dwc2.py
>-rwxrwxrwx 1 pi pi 0 Dec 29 18:04 /home/pi/dwc2-for-klipper/web_dwc2.py

What about permissions here?
>pi@raspberrypi:~ $ ls -la  klipper/klippy/gcode.py
>-rw-r--r-- 1 pi pi 31164 Dec 29 18:25 klipper/klippy/gcode.py

Complete log: https://pastebin.com/AE2fTiiE

**Comment by AbomShep** [comment]
Just did a fresh install with the same result.

**Comment by Stephan3** [comment]
Your file is missing or the link is miss pointing

**Comment by AbomShep** [comment]
You'd think right? as shown above everything shows correctly.

**Comment by Stephan3** [comment]
There is no other reason why a klippy instance is reporting invalid config section
