### ISSUE TITLE
Big gcode file wrong stats calculation

### ISSUE THREAD

**Issue by ZhenyaKa** [Stephan3/dwc2-for-klipper#46]
If you want I can share that file
![kiss_51kb 1579702403](https://user-images.githubusercontent.com/28926895/72901323-9ecf3a80-3d3a-11ea-9c5d-ab72ce7f749f.jpg)

**Comment by Stephan3** [comment]
Pls upload the gcode file. Theese are Slicer not supported values

**Comment by ZhenyaKa** [comment]
Here
[Крышка-проводов-для-Сергея.gcode.zip](https://github.com/Stephan3/dwc2-for-klipper/files/4097877/-.-.-.gcode.zip)

**Comment by Stephan3** [comment]
well, i uploaded that gcode and it just worked. Dont know what to say ?

![image](https://user-images.githubusercontent.com/47381132/72925845-abac5800-3d53-11ea-815a-4744b8f6bf29.png)

**Comment by Stephan3** [comment]
it just works for me, you never went bakc. so i assume its working -> close.
