### ISSUE TITLE
Cancel job routine

### ISSUE THREAD

**Issue by ozligia** [Stephan3/dwc2-for-klipper#5]
Hi Stephan, great work! Switched to dwc2 as it is much better than octoprint.

Is there a way to support cancel job routine, like lift head up and move to parking position and then disable heaters and motors?

**Comment by Stephan3** [comment]
its on the list, yes. I plan to use the rrf mechanics, mixed up with kipper macros. Be patient, this code is about 3 weeks old :)

**Comment by Stephan3** [comment]
As the functionality is there now -> closed.
