### ISSUE TITLE
Network Connection error and DWC2 crashes uploading large Gcode

### ISSUE THREAD

**Issue by GhostlyCrowd** [Stephan3/dwc2-for-klipper#50]
I have a very detailed large gcode of 702mb, when attempting to upload i get a network error and it crashes dwc2 instantly, if i scp the file to dwc2 and then refresh the gcode list then it crashes dwc2 as soon as it starts scanning the file. 

Octoprint seems to handle the gcode fine. 

Is their a file size or complexity limit for this?

**Comment by antst** [comment]
I also have crash, once file is uploaded (in my car it is about 100 MB files). But file received fully, and after restart I am able to print them from G-codes directory.

**Comment by Stephan3** [comment]
Please provide a log

**Comment by Stephan3** [comment]
No log -> so i close this now
