### ISSUE TITLE
Page Not Found After Adding callback for gcode responses

### ISSUE THREAD

**Issue by NedalLive** [Stephan3/dwc2-for-klipper#51]
Hello,
After installation I had access to the web page, however it did not seem to communicate with Klipper.
![image](https://user-images.githubusercontent.com/37265911/75612854-cd091c80-5b27-11ea-8650-d8756f8556bb.png)

I therefore carry out the modification operation of the gcode.py file by hand, after this modification it is impossible to find the web page ...
I tried to redo an installation from the beginning without success

**Comment by Stephan3** [comment]
Please provide a log.

**Comment by NedalLive** [comment]
my problem comes from editing the file by hand with Notepad ++ it added tabulation etrage ...
Corrected in ssh is the problem is solved
