### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by NedalLive** [Stephan3/dwc2-for-klipper#55]
You did a great job! thank you for that it is a real pleasure to no longer use Octoprint! the installation is still a little complex and is not accessible to everyone unfortunately.

Is it possible to add a dragged and dropped function to load a .gcode file when we are in the Jobs tab?

**Comment by Stephan3** [comment]
That sounds like a feature for the Webinterface itself. This has nothing to do with the translator.

https://github.com/chrishamm/DuetWebControl
