### ISSUE TITLE
suppress specific klipper messages

### ISSUE THREAD

**Issue by nitej** [Stephan3/dwc2-for-klipper#57]
is there any way to suppress some of the messages klipper sends? particularly for the mesh bed measurements? klipper produces one message per measurement, which translates into 27 popups in dwc with a 3x3 mesh and 3 sample points. quite annoying. maybe some regex filters for klipper messages?

**Comment by Stephan3** [comment]
You can implement this as you like. Just fork and do what you want. Happy coding.
