### ISSUE TITLE
Suggestion: could the functionality of the OctoPrint-Cancelobject plugin be added?

### ISSUE THREAD

**Issue by thiagosfsilva** [Stephan3/dwc2-for-klipper#59]
I have just switched to Klipper and am using DWC2 instead of Octoprint. It is overall a vastly improved UI, but if there is one quality-of-life feature that miss from Octoprint is the Cancel Object plugin. Typing this now as I babysit a print where one object of 11 has failed and I am trying to salvage as it goes.

I don't know how much work it would be to add, but thought I would leave the suggestion. If I knew more Python and web programming I'd be happy to help.

**Comment by Stephan3** [comment]
We had that discussion earlier. Plugin feature request goes to DWC, not this translator. Thanks
