### ISSUE TITLE
After installation I have errors in log file

### ISSUE THREAD

**Issue by Kotletowsky** [Stephan3/dwc2-for-klipper#60]
![err](https://user-images.githubusercontent.com/56607153/78457077-01807300-76a8-11ea-82a9-1c23ed22ec94.jpg)
And I can't start dwc. Webmenu is loaded, but still  blinking. And get message: o.temps.state is undefined

**Comment by Stephan3** [comment]
Please try to read the text of the error message, thanks.

**Comment by Kotletowsky** [comment]
But I have value in z_offset. I had DWC2 working before new installation, printer.cfg it's the same

**Comment by Stephan3** [comment]
The config parser is telling a different story. This has nothing to do with dwc.

**Comment by Kotletowsky** [comment]
I change offser from -1 to 0 and it's work. 
But there is anoter problem. I want to execute firmware_restart from console and I get:
JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 22 of the JSON data

**Comment by Stephan3** [comment]
provide the log. cant answer to that

**Comment by Kotletowsky** [comment]
[klippy.log](https://github.com/Stephan3/dwc2-for-klipper/files/4563023/klippy.log)
still getting json parse errors

**Comment by rafaljot** [comment]
and config, pls.

**Comment by rafaljot** [comment]
You need to clean up the config.
The last section [gcode_macro end_g] is mixed up with [web_dwc2], [virtual_sdcard] etc.

Remove all characters after last section like ====== etc
You may have corrupted data after #*# <---------------------- SAVE_CONFIG ---------------------->
So remove lines and calibrate printer again

**Comment by Kotletowsky** [comment]
json problems moved to another topoic
