### ISSUE TITLE
Using two printers simultaneous - OSError: [Errno 11]

### ISSUE THREAD

**Issue by Henke1983** [Stephan3/dwc2-for-klipper#63]
I want to be able to use more than one printer in one Raspberry Pi to drive Klipper. 
I have successfully installed DWC2-for-klipper with the modification that needed. 
The printers have different port-numbers to connect to, and they are possible to use.  
The guide I followed was this one : https://klipper.info/klipper-+-dwc2-1/installing-dwc2
In there is some code that are inserted into the gcode.py file. This is located at row 324. 
So in the dwc2 I don't get any feedback on the second printer in the gcode-console. It's just a spinner waiting for feedback from printer(on the send button)
The printer on port 4750 works fine. 
The printer on port 4760 works - but after some commands I get OSerror. 

The error from Klippy2.log.
_Write g-code response
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 324, in respond
    os.write(self.fd, msg+"\n")
OSError: [Errno 11] Resource temporarily unavailable_

Can you help me sort this out - because then I can connect additional printer to DWC2 and Klipper. Is it any more information needed. 
[klippy2.log](https://github.com/Stephan3/dwc2-for-klipper/files/4458229/klippy2.log)

**Comment by Stephan3** [comment]
Two instances of Klipper with dwc2 are running just fine. Please make sure you sorted the paths for both instances out correctly.
