### ISSUE TITLE
internal server error 500

### ISSUE THREAD

**Issue by Kotletowsky** [Stephan3/dwc2-for-klipper#69]
Every time, when I want to send cmd by console, I get internal server error 500 message.
Especially, when I click something in Z babystepping.
How to solve that ?

**Comment by rafaljot** [comment]
log pls.

ps: zapraszamy na reprapy.pl

**Comment by Kotletowsky** [comment]
[klippy.log](https://github.com/Stephan3/dwc2-for-klipper/files/4563586/klippy.log)

[printer_cfg.txt](https://github.com/Stephan3/dwc2-for-klipper/files/4563599/printer_cfg.txt)

**Comment by rafaljot** [comment]
1. As I said in before, clean up the config first. Remove this line and all after 
```
#*# <---------------------- SAVE_CONFIG ---------------------->
```
Don't write any configuration manually after this line in the future.

2. I'm not sure you can use comments in this way in macro.
```
[gcode_macro start_g]
gcode:
   G28
#   BED_MESH_CLEAR
#   BED_MESH_PROFILE LOAD=ENDER3
```
Delete these comments please.

**Comment by Kotletowsky** [comment]
deleted, cleaned. Still, when I want to use babystep: 
![Clipboard02](https://user-images.githubusercontent.com/56607153/80869181-27953500-8c9f-11ea-9fe3-e8943611d338.jpg)

**Comment by rafaljot** [comment]
try the same using Octoprint. We'll find out if the problem is with DWC2 or Klipper.
It works for me:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/13086437/80870370-54991600-8ca6-11ea-9ad4-2c31ed5cbbda.png">

**Comment by Stephan3** [comment]
@Kotletowsky 
You logfile dos not contain a M290 . If we want to analyse your problem, we need a valid log here, thanks.

**Comment by brycedjohnson** [comment]
Saw the same error when trying to set the hot bed.  New dwc2 install coming from an octoprint/octopi. 
![image](https://user-images.githubusercontent.com/2583801/81212306-f021d380-8f91-11ea-97b6-173d1fd9ae21.png)
[klippy.log](https://github.com/Stephan3/dwc2-for-klipper/files/4588619/klippy.log)

**Comment by brycedjohnson** [comment]
My issue went away by reverting to older klipper, the same as this one: https://github.com/Stephan3/dwc2-for-klipper/issues/72#issuecomment-624814547
