### ISSUE TITLE
Extrusion control disabled

### ISSUE THREAD

**Issue by shaiss** [Stephan3/dwc2-for-klipper#7]
Extrusion control is disabled.   Even when the extruder is at 220 (above the min extrusion temp) and g1 e100 f300 works, these buttons in dwc are disabled.  

Screenshot http://imgur.com/IDvkPl7

**Comment by Stephan3** [comment]
try latest master. It should work now. it lso adds multitool support. please report back after testing.

**Comment by shaiss** [comment]
Awesome and ty!

**Comment by shaiss** [comment]
@Stephan3 I just did a pull and am now getting an error re current_tool.  I presume an update is required to the printer.cfg?

`Warning:  Klipper state: Shutdown
4/11/2019, 3:49:25 PM: STATUS: Warning:  Internal error during ready callback: web_dwc2 instance has no attribute 'current_tool'
Warning:  Once the underlying issue is corrected, use the
Warning:  "FIRMWARE_RESTART" command to reset the firmware, reload the
Warning:  config, and restart the host software.
Warning:  Printer is shutdown
Warning:  Klipper state: Not ready
Error:  Internal error during ready callback: web_dwc2 instance has no attribute 'current_tool'`

**Comment by mtsgsd** [comment]
I found this as well.
`Uncaught exception GET /rr_status?type=1 (192.168.1.111)
HTTPServerRequest(protocol='http', host='192.168.1.114:4750', method='GET', uri='/rr_status?type=1', version='HTTP/1.1', remote_ip='192.168.1.111')
Traceback (most recent call last):
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 247, in get
    self.web_dwc2.rr_status_1()
  File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 663, in rr_status_1
    "currentTool": self.current_tool,   #       must be at least 1 ! learned the hardway....
AttributeError: web_dwc2 instance has no attribute 'current_tool'`

**Comment by Stephan3** [comment]
Have you guys tries to read that pile of words on your own? Please post a log next time in readable format. Thanks

try latest master now

**Comment by shaiss** [comment]
@Stephan3 I pulled the master but now seems the klipper console goes through and endless restart cycle.  I noticed "AttributeError: web_dwc2 instance has no attribute 'sdcard'" in the logs.  pictures attached for better readability.
<img width="1259" alt="Screen Shot 2019-04-12 at 08 02 57" src="https://user-images.githubusercontent.com/113060/56036130-15460300-5cfa-11e9-80e5-732b697fccb2.png">
<img width="856" alt="Screen Shot 2019-04-12 at 07 46 32" src="https://user-images.githubusercontent.com/113060/56036131-15de9980-5cfa-11e9-9376-6208d9bad3a6.png">

**Comment by Stephan3** [comment]
I need to do it on my machine. It is in parts currently

**Comment by shaiss** [comment]
@Stephan3 np, let us know how we can help testing.
for now I've rolled back to commit 707bab4 as that one works.

**Comment by mtsgsd** [comment]
Just an FYI, I have the rolling messages, but no errors in the log.

**Comment by Stephan3** [comment]
I rolled back to earlier version for now. Theese reconnects happen when dwc webapp errors. you can see the log of dwc when you press strg+shift+i in your browser. theres a console opening then shows whats happening.

**Comment by shaiss** [comment]
@Stephan3 looks like issue #8 is the proper place for the reconnect problem @mtsgsd and I are reporting.

If we go back to the root of this issue, extrusion control being disabled, is that fixed in the latest commit and we should verify then close this ticket, or is that still an issue?

not trying to pressure, just trying to help make sure we have these issues cleaned up.

**Comment by Stephan3** [comment]
The confusion basicaly was initiated by pushing untested code. my printer(voron 2) works with the current version on github.

**Comment by Stephan3** [comment]
I am late to the party but try the current master pls. @shaiss

**Comment by shaiss** [comment]
Will do. I'll git pull and let you know!

**Comment by Stephan3** [comment]
@shaiss  any news? should work? Can i close this?

**Comment by shaiss** [comment]
Crud I forgot. Let me check tomorrow and get back to you.
