### ISSUE TITLE
Issue with DELTA_ANALYZE CALIBRATE=extended

### ISSUE THREAD

**Issue by centuryrehab** [Stephan3/dwc2-for-klipper#70]
When I enter DELTA_ANALYZE CENTER_DISTS=73.65,73.50,73.2,73.28,73.3,73.5 as step 1 it does not do anything.
It just spins and spins.

**Comment by Stephan3** [comment]
Cant tell anything wihout a valid log, thanks.

**Comment by exxperto** [comment]
I think he mean that after send command in terminal he got running line under input window. Sometimes it happens when doing serial commands TESTZ Z=... in calibrating. In that case I make page refresh.
