### ISSUE TITLE
I installed klipper + dwc2 can't start webserver

### ISSUE THREAD

**Issue by gustavya** [Stephan3/dwc2-for-klipper#78]
Hello everyone, I installed klipper+dwc2 and finally flashed a powerspec pro(same as FFCP)

I have the following error in the log file, I guess it's why I can't see the webserver.

Unhandled exception during connect
Traceback (most recent call last):
File "/home/pi/klipper/klippy/klippy.py", line 136, in _connect
self._read_config()
File "/home/pi/klipper/klippy/klippy.py", line 129, in _read_config
self.load_object(config, section_config.get_name(), None)
File "/home/pi/klipper/klippy/klippy.py", line 118, in load_object
self.objects[section] = init_func(config.getsection(section))
File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 1684, in load_config
return web_dwc2(config)
The RPI seems connected and the board flashed fine, since I can see movement in the lcd, like a wave of lines flowing.

Any advice?
TIA

Gus

**Comment by maketo3D** [comment]
The same problem here, starting from a clean installation and with a printer.cfg working with octoprint.

**Comment by pierre-vo** [comment]
What version of dwc are you using? readme mentions 2.1.6, is it possible you took something newer?
Edit: is it possible the error message is not complete? There seem to be a change in klipper that requires some adaption in the instructions, it is discussed here: https://github.com/Stephan3/dwc2-for-klipper/issues/73

**Comment by maketo3D** [comment]
This worked for me.
https://github.com/Stephan3/dwc2-for-klipper/pull/79

**Comment by shaiss** [comment]
> This worked for me.
> #79

confirmed that works too!

**Comment by Stephan3** [comment]
fixed
