### ISSUE TITLE
the download link for DWC2 appears to be broken

### ISSUE THREAD

**Issue by shiftingtech** [Stephan3/dwc2-for-klipper#80]
Trying to install as per readme.md, the wget for DWC2 results in a 404.

Looking at the DWC git, it looks like there are currently only SDC releases up to 2.1.4.

**Comment by exxperto** [comment]
Try to use https://github.com/manu7irl/klipper-DWC2-installer
It working now...

**Comment by manu7irl** [comment]
Nice to know thanks!

**Comment by jjuuzzii** [comment]
I can’t run installer.sh 
I get permission error

**Comment by manu7irl** [comment]
From my repo?

**Comment by jjuuzzii** [comment]
Yes. 
How do I use the chmod command ? 
chmod +x ./installer doesn’t seem to work.

**Comment by manu7irl** [comment]
Post issues in my repo. Why here?

**Comment by shiftingtech** [comment]
> Try to use https://github.com/manu7irl/klipper-DWC2-installer
> It working now...

No thanks.  I have it working just fine.  I just posted the bug report so that Stephan3 can hopefully update the readme...
