### ISSUE TITLE
UNKNOWN STEPPER

### ISSUE THREAD

**Issue by JartX** [Stephan3/dwc2-for-klipper#83]
<img width="394" alt="Captura de pantalla 2020-05-24 a las 2 40 16" src="https://user-images.githubusercontent.com/8399211/82743189-2cae4700-9d68-11ea-9815-a0adc85dfef9.png">

Problem on SKR 1.3 and Robin Nano

**Comment by Stephan3** [comment]
fixed

**Comment by JartX** [comment]
Many thanks @Stephan3
