### ISSUE TITLE
Error when editing System - config.g

### ISSUE THREAD

**Issue by mejobloggs** [Stephan3/dwc2-for-klipper#84]
When I try update my config file

- Change printer name
- I click save
- It asks if I want to restart board to apply changes, click Yes
- I get "Error:  'dict' object has no attribute 'get_commandline'"

Everything else seems to be working fine.

I'm pretty noob, sorry if it's me just doing something wrong

**Comment by Kotletowsky** [comment]
Already have the same. After fresh install.

**Comment by pluuuk** [comment]
This is because Klipper updated their gcode.py API and Stefan hasn't reviewed PR #75 , please clone this repo and give it a try: https://github.com/pluuuk/dwc2-for-klipper.git

**Comment by Stephan3** [comment]
fixed
