### ISSUE TITLE
Jog Command Toolbar Hidden

### ISSUE THREAD

**Issue by ghost** [Stephan3/dwc2-for-klipper#87]
Hi, I am trying to get the jog command bar to appear but I cannot work out how. When I first load the DWC2 interface the box appears but then it disappears. 
![no jog](https://user-images.githubusercontent.com/41510447/84451822-81721d00-ac97-11ea-9b35-23c55c2ef34d.png)
Reading the manual, https://duet3d.dozuki.com/Wiki/Duet_Web_Control_Manual 
It says the interface is dynamic and features will only appear if they are configured. My issues is how do I configure the features I want to show? That part for some reason is not in the manual.

![dwc2 jog](https://user-images.githubusercontent.com/41510447/84451736-3eb04500-ac97-11ea-80b5-70012a3f9d1d.png)

Thanks for any help.

**Comment by BlackStump** [comment]
Look at your Status => OFF 
When klipper is happy you will see what you are looking for.
I suggest you have a look at the klippy.log to see what your problem is

**Comment by ghost** [comment]
Thanks, I have worked out that I have bigger problems. My log file is showing a MCU problem.
