### ISSUE TITLE
'dict' object has no attribute 'get_commandline'

### ISSUE THREAD

**Issue by alf249** [Stephan3/dwc2-for-klipper#93]
Hi guys, I have been trying to set up DWC2 for my printer.
I have been running Klipper + OctoPi for almost a year without any issues.

I decided to start from scratch, so I followed installation instructions on:
https://klipper.info/klipper-+-dwc2-1/installing-klipper

HOME ALL button works, but temperatures and macros do not work.

Klipper looks ok:
https://klipper.info/klipper-+-dwc2-1/installing-klipper

These are the error codes I am getting after clicking on macros:
'dict' object has no attribute 'get_commandline'
'dict' object has no attribute 'get_command'

I have also tried to install OctoPrint + DWC2 and I get the same errors.

This is my klippy.log: lpomykal.cz/download/klippy.log

Could you help me?
Thanks.

**Comment by Stephan3** [comment]
fixed
