### ISSUE TITLE
Gcode upload inserted random characters into gcode file

### ISSUE THREAD

**Issue by ju-sti** [Stephan3/dwc2-for-klipper#97]
The printing of a job stopped suddenly today with this error:![image](https://user-images.githubusercontent.com/32344034/87229267-0770a900-c3a7-11ea-92c5-631d33a3f86e.png)

I uploaded the printed gcode file with dwc to my printer.
After I downloaded the gcode file from the printer to check what is wrong I noticed the issue immediately:
![image](https://user-images.githubusercontent.com/32344034/87229271-122b3e00-c3a7-11ea-82b4-4a6b464aa9aa.png)

The original file as created by Cura has proper content.  Hostname of the RPi where dwc2 for klipper is running is "raspi-print".

So I very much suspect that either uploading or printing the file in dwc has corrupted the file by inserting weird bytes and the hostname for some reason.

**Comment by ju-sti** [comment]
* I'm using dwc2-for-klipper version with the "add mutex to gcode ecxecution. try to fix the one command behind" change
* Uploading the gcode and downloading it again did not lead to the same error. The file did not have changed content as far as I can see.

**Comment by Stephan3** [comment]
okay thats odd. i was not able to reproduce this.

**Comment by Stephan3** [comment]
I tried today to provoke this using a pi zero and i had just thrown things at it as much as possible. No matter how hard i try, i am not able to make this happen.
Did that ever happen again?

**Comment by ju-sti** [comment]
Thanks for trying. I "uploaded and started" at least 30 times since that error occurred but the error did not happen again.

**Comment by Stephan3** [comment]
I definitley cant reproduce it. Sorry.
