### ISSUE TITLE
DWC UI working, won't connect to printer?

### ISSUE THREAD

**Issue by rlesac** [Stephan3/dwc2-for-klipper#98]
Hi!
Installed 3.1.1 DWC, configured the printer.cfg, I can get the UI to show up in the browser, but the printer is always off.
I see no issues in the klippy.log
Octoprint works fine, If I connect to Octoprint, I can see the console data in DWC, but that's about it.

The only thing that seems to work is loading the height map.

The status panel is "twitchy", it will change height every few seconds.

Any suggestions?

**Comment by Stephan3** [comment]
off is detected if printer state is not ready. have you tried a firmware_restart ?

**Comment by rlesac** [comment]
> off is detected if printer state is not ready. have you tried a firmware_restart ?

I have, but it doesn't change anything.

If I try Octoprint, Octoprint connects just fine.

Here's my klippy.log with the printer.cfg

[dwc-debug1.log](https://github.com/Stephan3/dwc2-for-klipper/files/4925555/dwc-debug1.log)
Here is a short video: https://youtu.be/MMc1mo7M7xo

**Comment by rlesac** [comment]
Any ideas what to try next?

**Comment by Stephan3** [comment]
I am verry sorry. I just picked your config and put it on my testmachine. I had to comment out display and bltouch ad its not there on the testsystem. It just worked. Can you try to comment out display and bltoch and report back?

**Comment by saxmfone1** [comment]
I've just installed this and ran into the same issue. Seeing this error in the logs, while the screen flashes between connected and not connected:
```Uncaught exception GET /rr_status?type=2 (192.168.86.24)
HTTPServerRequest(protocol='http', host='192.168.86.29:4750', method='GET', uri='/rr_status?type=2', version='HTTP/1.1', remote_ip='192.168.86.24')
Traceback (most recent call last):
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 255, in get
    self.web_dwc2.rr_status_2()
  File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 740, in rr_status_2
    gcode_stats = self.gcode.get_status(now)
AttributeError: GCodeDispatch instance has no attribute 'get_status'
DWC2:59557.11 - 192.168.86.24 - GET - /rr_connect?password=reprap&time=2020-8-23T1%3A12%3A37
```

I commented out bltouch and display, and this gets the system connected. However it rightly complains about missing bltouch config.

**Comment by Stephan3** [comment]
latest maste is broken since few days

```
cd klipper
git reset --hard 560d48d
sudo service klipper restart
```

**Comment by saxmfone1** [comment]
Ah, thank you, that solves it.
