### ISSUE TITLE
regex support superslicer

### ISSUE THREAD

**Issue by robthide37** [Stephan3/dwc2-for-klipper#99]
for some reason object height is showing as the first layer height . I had switched out superslicer and slicer pe edition in past and it worked but when updated it overwrote my edits and now for some reason that its added it isn't reading the layer height .

**Comment by Stephan3** [comment]
please provide the gcode file. Thanks

**Comment by Stephan3** [comment]
meanwhile i downloaded superslicer and checked things out. regex is working as ecxpected. Thanks. 

-> close

**Comment by robthide37** [comment]
[yoda.curved.gcode.txt](https://github.com/Stephan3/dwc2-for-klipper/files/4978003/yoda.curved.gcode.txt)
here is one

**Comment by robthide37** [comment]
i missed you response but if you need more i can make more it seems random. fist i thought it was if the first layer was dif but that doesn't seem to be the case. Also i made sure that no adaptive layers or anything were on .

**Comment by robthide37** [comment]
![image](https://user-images.githubusercontent.com/64717944/88491127-c95eb200-cf6e-11ea-80d1-959c67571f46.png)
[MeshBody27.gcode.txt](https://github.com/Stephan3/dwc2-for-klipper/files/4978832/MeshBody27.gcode.txt)
another example of it reading wrong
